language: python
env: # These should match the tox env list
    - TOXENV=py

before_install:
    - pip install --use-mirrors mysql-python==1.2.5 python-ldap==2.4.13

install: pip install tox --use-mirrors
script: tox
